---
title: "chap 11. stringr로 하는 문자열"
author: "dayoung"
date: '2020 10 5 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




11.1.1 준비하기

library(tidyverse)
library(stringr)



## 11.2 문자열 기초
작은 따음표나 큰따음표로 문자열을 생성할수있다.
string1 <- " 문자열입니다"
string2 <- " 문자일 내에 "인용문"이 포함된 경우. 나는 작은 따음표로 사용한다.

따옴표 닫는 것을 잊어 버린 경우, 연속문자(continuation character)인  +  가 나타난다.
> "닫는 따옴표가 없는 문자열이다
+    
+    
+ 도와줘요 갇혔어요

이 같은 일이 발생했다면 이스케이프키를 누르고 다시 시도하라!

작은따옴표 문자나 큰따옴표 문자를 문자열에 포함하려면 ‘벗어나기 (escape)’ 위해  \  (이스케이프 키)를 사용할 수 있다

double_quote <- "\"" # or '"'
single_quote <- '\'' # or "'"

같은 원리로 역슬래시 문자를 포함하려면  "\\"  과 같이 두 번 입력해야 한다.

문자열의 출력 표시는 문자열 자체와 같지 않다는 것에 주의하라. 출력에선 이스케이프가 보이기 때문이다. 문자열의 원시 형태를 보려면  writeLines()  를 사용하라.
x <- c("\"", "\\")
x
#> [1] "\"" "\\"
writeLines(x)
#> "
#> \

이 외의 특수 문자들도 매우 많다. 줄바꿈,  "\n"  , 탭,  "\t"  은 가장 일반적인 것들이다.  ?'"'  , 혹은  ?"'"  로 볼 수 있는 도움말을 통해 전체 목록을 볼 수 있다. 또한  "\u00b5"  과 같은 문자열을 간혹 볼 수도 있는데, 이는 비영어 문자를 모든 플랫폼에서 동작하도록 작성한 것이다.

x <- "\u00b5"
x
#> [1] "µ"



c()로 만들수있는 문자형 백터를 이용하면 복수의 문자열을 나타낼 수 있다.

 c("one", "two", "three")
#> [1] "one"   "two"   "three"

## 11.2.1 문자열 길이
-이 함수들의 이름은 더 직관적이며 모두 str_로 시작한다. 
-예륻 들어 str_length()는 문자열의 문자 개수를 알려준다.

str_length(c("a", "R for data science", NA))
#> [1]  1 18 NA

-공통된 str_접두사는 RStudio 이용자에게 특히 유욯하다.


## 11.2.2 문자열 결합
-둘 이상의 문자열 결합때는 str_c()를 사용하라.

str_c ("x" , "y")
#> [1] "xy"

str_c("x", "y", "z")
#> [1] "xyz"

-구분 방식을 조정할 때는 sep 인수를 사용하라.
str_c("x", "y", sep = ",")


- 결측값을 "NA" 로 출력하길 원하면 str_replace_na()를 사용하라.
x <- c("abc", NA)
str_c("/-", x, "-/")
str_c("/-", str_replace_na(x), "-/")


- 앞의 코드 에서 본 것처럼 str_c()는 백터화되고 짧은 백터가 긴 백터와 길이가 
              갈도록 자동으로 재사용한다.
              
            
str_c("prefix-", c("a", "b", "c"), "-suffix")   

- 길이가 0인 객체는 조용히 삭제된다. 이 특성은 if와 함께 쓰면 특히 유용하다.

name < - "Hadley"
time_of_day <- morning
birthday <- FALSE

str_c ("Good", time_of_day, "," name,
        if (birthday)" and HAPPY BIRTHDAY, ",")


##11.2.3 문자열 서브셋하기
- 문자열의 일부는 str_sub()를 사용하여 추출할 수 있다.
x <- c("Apple", "Banna", "Peer")
str_sub(x,1,3)
# 음수는 끝에서부터 반대 방향으로 센다
str_sub(x,-3,-1)

str_sub()는 문자열이 너무 짧은 경우에도 오류가 발생하지 않고 가능한 만큼 반
    환한다는 것을 주목하라.
    
str_sub("a", 1,5)    

str_sub()의 할당 형식을 사용하여 문자열을 수정할수있다. 
str_sub(x,1,1) <- str_to_lower(str_sub(x,1,1))
x


##11.2.4 로캘
-앞서 str_to_lower()를 사용하여 텍스트를 소문자로 변경했다.
- str_to_uper() 또 는 str_to_title()을 사용할 수도 있다.
# 터기어는 i가 점이 있는 것과 없는 것 두 개이다. 
# 또한 대문자도 다르다.
str_to_upper(c("i", "I"))
str_to_upper(c("i", "I"), locale = "tr")

- 베이스 R의 order()와 sort() 함수는 현재 로캘을 사용하여 정렬한다,

x <- c("apple", "eggplant", "banana")
str_sort(x, locale = "en") # 영어    
str_sort(x, locale = "haw") # 하와이어


***11.2.5 연습문제***

1. stringr을 사용하지 않는 코드에서 paste()와 paste()을 종종 볼 것이다. 두 함수
 의 차이점은 무엇인가? 이들중애 상응하는 stringr 함수는 무엇인가?
 이 함수들은 NA를 다를 때 어떻게 다른가?
2. str_c()의 sep 인수와 collapse 인수의 차이를 자신의 말로 기술하라. 
3. str_length()와 str_sub()을 이용하여 문자열 중앙 문자를 추출할. 문자열에
 짝수 개의 문자가 있다면 어떻게 하겠는가?
4.str_wrap()의 기능은 무엇인가? 어떤 경우에 이함수를 사용하겠는가?
5. str_trim()의 기능은 무엇인가? str_trim()의 반대는 무엇인가?
6. 예를 들어 백터 c("a", "b","c")를 문자열  a,b,c로 변환하는 함수를 작성하라.
    길이가 0,1,2인 백터일 경우 어떻게 해야 하는지에 대해 생각해보라.
    
##11.3 정규표현식을 이용한 패턴매칭
-정규표현삭은 문자열의 패턴을 기술하는 매우 간결한 언어이다.
 -이해하는 데 다소 시간이 걸리지만 한번 이해하면 매우 유용함을 알 수 있을것이다,
 
 
 ##11.3.1 기초패칭
 -가장 간단한 패턴은 문자열 전체(exact) 매칭이다.
 
 
 install.packages("htmlwidgets")
 x <- c("apple","banana", "peer")
 str_view(x, "an")

다음으로 간단한 단계는 (줄바꿈을 제외한) 임의의 문자와 매칭하는.이다.
str_view(x,".a.")

정규표현식/.를 작성하기 위해서느 문자열 "//." 이 필요하다.
# 정규표현식을 생성하기위해 //이 필요함
dot <- "//."
# 그러나 이 정규표현식 자체는 역슬래시를 하나만 갖게됨

writelines(dot)
#> /.
# R에서 .을 정확하게 찾는 방법
str_view(c("abc", "a.c", "bef"), "a//.c")


-정규표현식에서 /를 이스케이프 문자로 사용한다면 문자 /는 도대체 어떻게 
    매칭하겠는가?
_ 정규표현식 //를 만들어 이스케이프해야한다.

x <- "a//b"
writeLines(x)
#> a/b
str_view(x,"////")
-이 책에서 정규표현식은 /.과 같이 쓰고 정규표현식을 나타내는 문자열 "//." 과
     같이 쓸 것이다.


***11.3.2 연습문제***

1. 다음의 각 문자열 "/", "//", "///"가 /와 매칭되지 않는 이유를 설명하라.
2. 시퀀스 "/를 어떻게 매칭하겠는가?
3. 정규표현식 /../..은 어떤 패턴과 매칭되겠는가? 문자열로 어떻게 표현하겠는가?

## 11.3.3 앵커
- 기본적으로 정규표현식은 문자열의 어떤 부분과도 매칭될 수 있다.
- 이럴 때는 다음 문자를 사용할 수 있다.
. ^: 문자열의 시작과 매칭
. $: 문자열의 끝과 매칭

x <- c("apple", "banana", "pear")
str_view(x, "^a")

str_view(x, "a$")

다음의 연상 구문을 시도해보자. 파워(^)로 시작하면 , 돈($)으로 끝나게 된다.

x <- c("apple pie", "apple", "apple cake")
str_view(x, "apple")
str_view(x, "^apple$")


***11.3.4 연습문제***
1. 문자열"$^$" 어떻게 매칭하겠는가?
2. strignr::words에 담긴 평범한 말뭉치(corpus)에서 다음에 해당하는 단어들을 
     찾는 정규표현식을 구하라.
a. "y"로 시작

b. "x"로 끝남

c. 정확히 세 글자. (str_length()를 사용하는 부정행위를 하지 말것!)

d. 7개 이상의 글자.

이 리스트는 길기 때문에 str_vie()의 match 인수를 이용하여 매칭되는 단어 들만, 
      혹은 매칭되지 않는 단어들만 볼 수 있다.
      
## 11.3.5 문자 클래스와 대체구문
- 하나 이상의 문자를 매칭하는 특별한 패턴들이 많이 있다.
. /d는 임의의 숫자와 매치한다.
. /s는 임이의 여백 문자(whitespace, 예를 들어 공백, 탭, 줄바꿈)와 매치한다.
. [abc]는 a,b또는 c 를 제외한 임의의 문자와 매치한다.
. [^abc]는 a,b 또는 c 를 제외한 임의의 문자와 매치한다.

/d나 /s를 포함하는 정규표현식을 만들기 위해서는 해당 문자열에서 /를 이스케이프
    해야 하므로"//d"나 "//s 로 입력해야 한다는것을 기억하라.
str_view(c("grey", "gray"),"gr(e/a)y")    


***11.3.6 연습문제***
1. 다음에 해당하는 모든 단어를 찾는 정규표현식을 작성하라.

a. 모음으로 시작함.

b. 자음만 포함함(힌트:'비-자음 매칭에 대해 생각해보라).

c. ed로 끝나지만 eed로 끝나지는 않음. 

d. ing 혹은 ize로 끝남.

2. 다음의 규칙을 데이터 기반으로 증명하라. 'c 뒤를 제외하고는 i가 e 앞에 온다.
3. 'q' 다음은 항상 'u'인가?
4. 미국 영어가 아닌 영국 영어로 쓰어진 단어를 매칭하는 정규표현식을 작성하라.
5. 여러분의 나라에서 일반적으로 쓰이는 전화번호를 매칭하는 정규표현식을
    작성하라.

## 11.3.7 반복
-다음단계는 패턴이 몇 회 매칭하는지를 조정하는것이다.
.?: 0또는 1회
.+: 1회 이상
.*: 0회 이상

x <- "1888 is the longest year in Roman numerals: MDCCCLXXXVIII
str_view(x, "CC?")
str_view(x, "CC+")


.{n}: 정확히 n회
.{n,}: n회 이상
.{,m}: 최대 m회
.{n,m}: n과m회 사이

str_view(x,"c{2}")


***11.3.8 연습문제***
1. ?,+,* 와 같은 의미의 정규표현식을 {m,n} 형식을 사용해 기술하라.
2. 다음의 정규표현식이 어떤 것과 매칭하는지를 말로 설명하라. (사용하는 것 이 
정규표현식인지 아니면 그것을 정의하는 문자열인지 주의 깊게 일고 확인하라.)
a. ^.* $

b."//{.+//}"

c./d {4}-/d{2}-/d{2}

d. "////{4}" 

3. 다음의 모든 단어를 찾느 정규표현식을 작성하라.
a. 세 개의 자음으로 시작.

b. 세 개의 이상의 모음이 연달아 있음.

c. 두 개의 이상의 모음-자음 쌓이 연달아 있음.

4. 다음의 초보자 정규표현식 십자말 풀이를 풀어보라.

##11.3.9 그룹화 역참조
- 앞서 괄호를 사용하여 복잡한 표현을 명확하게 하는 법을 배웠다. 
- 다음의 정규표현식은 두 글자가 반복되는 과일 이름과 매칭한다.

str_view(fruit,"(..)//1", match = TRUE)
(str_view()와 함꼐 쓰면 왜 유용한지 곧 알게 될 것이다.)

***11.3.10 연습문제***
1. 다음의 표현식이 어떤 것과 매칭할지 말로 설명한다.
a. (.)/1/

b."(.)(.)//2//1"

c. (..)/1

d. "(.).//1.//1"

e. "(,)(.)(.).*//3//2//1"

2. 다음의 단어와 매칭하는 정규표현식을 작성하라.

a. 같은 문자로 시작하고 끝남
b. 두 뮨자 반복이 있음(예를 들어 'church'는 'ch' 를 투번 반복).
c. 적어도 세 곳에서 반복되는 문자가 있음(예컨데, 'eleven'은'e'가 세 게).


## 11.4 도구
- 이 절에서는 다음을 수행하는 다양한 strigr 함수들은 배울것이다.
. 어떤 문자열이 패턴과 매칭하는지 결정
. 매칭의 위치 잦기.
. 매칭의 내용 추출.
. 매칭된 것을 새 값으로 교체
. 매칭 기반으로 문자열 분함.


##11.4.1 매칭 탐지
- 문자형 백터가 패턴과 매칭하는지 확인하려면, str_detect()를 사욯하라.

install.packages("detect")
x <- c("apple", "banana", "pear")
str_detect(x,"e")

- 논리형 백터를 수치형 맥략에서 사용할 경우, FALS는 0이 되고, TRUE는 1이 된다는것
을 명심하다.
- 긴 백터에서의 매치 결과가 궁금할 때는 sum() 과 mean() 을 유용하게 사용할수
있다.

# t로 시작하는 단어의 개수는?
sum (str_detect(words, "^t"))
# 모음으로 끝나는 단어의 비율은?
mean (str_detect(words, "[aeiou]$"))

# 모음이 최소 하나가 있는 단어 모두를 찾은 뒤 그 역을 취함
no_vowels_ 1 <- ! str_detect(words, "[aeiou]")
# 자음 (비-모음)으로만 이루어진 단어를 모두 찾음
n0_vowels_ 2 <- str_detect(words, "^[aeiou]+$")

-str_detect() 일반적으로 패턴과 매칭하는 요소를 선택하는 데 사용한다.
- str_subset()으로 이 작업을 수행할 수 있다.
words[str_detect(words, "x$")]

install.packages("subset")
str_subset(words,"x$")

그러나 가지고있는 문자열은 일반적으로 데이터프레임의 열일 것이므로. 대신 
fillter를 사용하는 것이 좋다.

install.packages("fillter")
fillter (str_detect(words,"x$"))

-str_count()는 str_detect()의 변형 함수이다.

intstall.packages("count")
x <- c("apple", "banana", "peer")
str_count(x, "a")

#단어당 모음 평균 개수는?
mean(str_count(words,"[aeiou"]))

-str_count()는 mustate()와 함꼐 쓰는 것이 자연스럽다.

df %>% 
  mutate(vowles = str_count(word, "[aeiou"), 
         consonants = str_count(word, "[aeiou"))
         

- 매칭들끼리 서로 겹치지 않는다는 것을 주의하라. 예를 들어 "abababa" 에서 "aba"
     패턴이 몇 번 매칭하는가? 정규표현식에선 세 번이 아닌 두 번이라고 답한다.

str_count("abababa", "aba")
str_view_all("abababa", "aba")

-str_view()의 용법에 주의하라.
-곧 배우겠지만 많은 stringr 함수는 쌍으로 제공된다.

##11.4.2 연습문제
1. 다음 문제들을 두 가지 방식으로 각각 풀어보라. 하나의 졍규표현식을 사용 해보고
 또 여러 str_detect() 호출을 결합해보라.
 
 a. x로 시작하거나 끝나는 모든 단어를 찾아라,
 b. 모음으로 시작하고 자음으로 끝나는 모든 단어를 찾아라.
 c. 각기 다른 모음을 하나 이상씩 포함하는 단어가 있는가?
 
 2. 어떤 단어가 가장 많는 모음을 갖는가? 어떤 단어가 모음의 비율의 가장 높은 
 은가?(힌트: 분모는 무엇인가?)
 
 ##11.4.3 매칭 추출
 
 - 매칭한 실제 텍스트를 추출하려면 str_extract()를 사용하라.
 - 이들은 stringr::sentences에서 제공된다.
 
 
length(sentences)
head(sentences)

color <- ("red", "orange", "yellow", "green ", "blue", "purple")
color_match <- str_c(color, collaps = "/")
color_match

-이제 색상을 포함하는 문장을 선택할 수 있고, 그런 다음 매칭된 색상이 무엇인지 
추출할 수있다.

has_color <- str_subset(sentence, color_match)
mathches <- str_extract(has_color, color_match)
head (matches)

-str_extract()는 첫 번째 매칭만 추출한다는 것을 주의하라. 
-매칭이 두 개 이상인 모든 문장을 우선 선택해보면 이를 가장 쉽게 볼 수 있다.

install.packages("htmlwidgets")
more <- sentences[str_count(sentences, color_match) > 1]
str_view_all (more, color_match)

str_exact(more, color_match)

-이는 stringr 함수의 일반적인 패턴이다. 
- 매칭 하나로 작업하면 훨씬 단순한 데이터 구조를 사용할 수 있기 때문이다.
- 매칭 모두를 얻으려먼 str_extract_all()을 사용하면 된다.

str_extract_all(more, color_match)
str_extract_all(more, color_match, simplify = TRUE)

***11.4.4 연습문제***
1. 앞의 예에서 매칭된 정규표현식이 색상이 아닌 "flickered"에도 매칭한 것을 
눈치챘을지 모르겠다. 이 문제를 해결하기 위해 정규식을 수정하라.
2. 하버드 문장 데이터에서 다음을 추출하라.
 
 a. 각 문장의 첫 번째 단어.
 b. ing로 끝나느 모든 단어.
 c. 모든 복수형.
 
 ## 11.4.5 그룹화 매칭
 - 이 장 앞부문에서 연산 우선순위를 명확히 할 목적과 역참조 목적으 괄호 사용에
  대하 이야기 했었다.
  
  noun <- "(althe) ([^ ]+)"
  has_noun <- sentences %^%
      str_subset(noun) %^%
      head(10)
has_noun %>%
str_extract(noun)

- str_exact()는 완전한 매치를 제공하는 반면, str_match()는 각각의 개별요소를 
제공한다.

has_noun %>% 
   str_match(noun)

-str_match()처럼 동작하지만 매치의 이름을 사용자가 지정하도록 하고, 그 각각
을 새로운 열로 배치한다.

install.packages("tidyr")
tibble(sentence = sentences) %>%
tidyr:: extract (
sentence, c("article". "noun"), "(a/the ([^ ]+)", remove  = FALSE)

-str_extract()처럼, 각 문자열의 모든 매치를 원한다면 str_match_all()이필요하다.


***11.4.6 연습문제***
1. 'one', 'two','three'등과 같은 '숫자' 다음에 오는 모든 단어를 구하라, 숫자와
단어 모두를 추출하라.
2. 줄임말은 모두 것이라. 아포스트로피(') 이전과 이후 조각을 분리하라.

## 11.4.7 매칭 지환

- str_replace()와 str_replaces_all()을 이용하여 매치를 새로운 문자열로 치환할
수 있다.

x <- c("apple", "pear", "banana")
str_replace(x, "[aeiou]", "-")

str_replace_all(x, "[aeiou]", "-")

-str_replace_all()을 사용하며 명명된 패터를 제공하여 다중 치환을 수행할 수 있다.

x <- C("1", "house", "2 cars", "3 people")
str_replace_all(x, c("1" = "one", "2" = two, "3" =" three))

-고정된 문자열로 지환하는 대신, 매치의 구성요소를 삽입하기위해 역잠조를 
사용할 수 있다.
-다음은 코드는 두 번째와 세 번째 단어의 순서를 바꾼다.

sentece %>%
    str_replace("[^ ]+) ([^ ]+) ([^ ]+)", "//1 //3 //2") %>%
    head(5)

***11.4.8 연습문제***    

1. 문자열의 모든 슬래시를 역슬래시로 지환하라.

2. replace_all()을 사용하여 str_to_lower()의 간단한 버전을 구헌하라.

3.단어의 첫 번째와 마지막 문자를 바꿔라. 여전히 단어가 되는 문자열은 무엇인가?

## 11.4.9 문자열 분할

- 문자열 조각으로 분할하려면 str_split()을 사용하면 된다.
- 예를 들어 문장을 단어로 분할할 수 있다.

sentences %>% 
  head(5) %>%
  str_split(" ")

- 각 구성요소가 포함하는 조각의 개수가 다를 수 있으므로, 이 함수는 리스트를 
반환한다.

"a/b/c/d" %>%
  str_split ("///" %>%)
  .[ [1] ]
  #> [1] "a" "b" "c" "d"

- 리스트를 반환하는 다른  stringr 함수처럼 simplify = TRUE를 사용하여 행렬을
반환할수 있다.

sentence %>% 
 head(5) %>%
 str_split(" ", simplify = TRUE)

-반환활 조각의  최대 개수를 지정할 수도 있다.
- 패턴으로 문자열을 분할하는 대신 boundary() 함수를 사용하여 문자, 줄 문장 혹은 
단어를 경계로 분할할 수도 있다.

x <- "This is a sentence. This another sentence".
str_view_all(x, boundary("word"))

***11.4.10 연습문제***
1." apples,pears, and bananas" 와 같은 문자열은 개별구성요소로 분할하라.

2. 왜 " " 보다 boundary("word")로 분할하는 것이 좋은가?

3. 빈 문자열("")로 분할하면 어떻게 되는가? 실험해본후, 설명서를 읽어보라.

## 11.5 기타 패턴 유형
- 문자열로 된 패턴을 사용하며 자동으로 regex()호출로 래핑된다.

#일반적인 호출(아래의 긴 호출과 같다)
str_view(fruit, "nana")
# 긴 호출
str_view(fruit , regex("nana"))

-regex()의 다른 인수를 사용하여 매치의 세부사황을 제어할 수 있다.
- igonore_case = TRUE를 하면 문자가 대문자나 소문자 형태 모두로 매칭된다.
 항상 현재의 로캘을 사용한다.

bananas <- c("banana", "Banana", "BANANA")
str_view(bananas, "banana")

str_view(bananas, "banana")

-multiline = TRUE를 하면 ^와 $이 전체 문자열의 시작, 끝이 아니라 각 라인의 
시작과 끝이 매칭된다.
X <- "Line 1/nLine 2/nLine 3"
str-extract_all(x, "^Line")

- comments = TRUE를 하면 복잡한 정규표현식을 이해하기 쉽도록 설명과 공백을
사용할 수 있게 된다.

- dotall = TRUE를 하면 . 이 /n을 포함한 모든 문자에 매칭된다.
regex() 대신 사용할 수 있는 함수가 세 가지 있다.

- fixed()는 지정된 일련의 바이트와 정확히 매치한다.

fixed()를 영어가 아닌 언어에 사용할 때는 조심하라. 

동잏하게 렌더링하지만 다르게 정의되었기 때문에 fixed()가 매치를 찾지 못 한다.

str_detect(a1, fixed(a2))

- coll()은 표준 대조(collation) 규칙을 사용하여 문자열을 비교한다.
- 대문자를 구분하지 않는 (case-insensitive) 매치를 수행할 때 유용하다.
# 따라서 대소문자를 구분하지 않는 매치를 수행할 경우
# 지역별 차이에 대해 조심해야 한다.

-str_split()에서 보았듯이 boundary()를 사용하여 경계를 매치할 수 있다.
- 다른 함수들과도 사용할 수 있다.
x <- "this is a sentence."
str_view_all(x, bounary("word"))

***11.5.1 연습문제***

1. regex()와 fixed()를 각각 사용하여, 어떻게 /를 포함하는 모든 문자열을 찿겠는가?

2. sentences 에서 가장 자주 나오는 다섯 가지 단어는 무엇인가?

##11.6 정규표현식의 기타용도
-베이스 R의 다음의 두 함수도 정규표현식을 사용한다.
. apropos()는 전역 환경에서 사용할 수 있는 모든 객체를 검색한다.
apropos("replace")

.dir()은 디렉터리에 있는 모든 파일을 나열한다.

head(dir(pattern = "//. Rmd$"))
(*.Rmd 같은 '글로브(globs) 패턴'에 익숙한 경우, glob2rx()를 사용하여 이를 
정규표현식으로 변화할 수 있다.)

##11.7 stringi
- stringr은 stringi 패키지 기반으로 만들어졌다.

***11.7.1 연습문제***
1. 다음을 수행하는 stringi 함수를 찾아라.

 a.단어의 수 계산. 
 
 b. 중복 문자열을 찾음
 
 c. 랜덤 텍스트 생성
 
 2. stri_sort()에서 정렬에서 사용할 언어를 어떻게 제어하겠는가?
